// <auto-generated />
using System;
using Gestion_Quirurgica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gestion_Quirurgica.Migrations
{
    [DbContext(typeof(GestionQuirurgicaContext))]
    [Migration("20260501013341_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.Cirujano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnosExperiencia")
                        .HasColumnType("integer")
                        .HasColumnName("anos_experiencia");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("especialidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("cirujanos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnosExperiencia = 15,
                            Codigo = "CIR-001",
                            Especialidad = "Cirugía General",
                            Estado = "Activo",
                            Nombre = "Dr. Roberto Vega"
                        },
                        new
                        {
                            Id = 2,
                            AnosExperiencia = 10,
                            Codigo = "CIR-002",
                            Especialidad = "Anestesiología",
                            Estado = "Activo",
                            Nombre = "Dra. Ana Condori"
                        },
                        new
                        {
                            Id = 3,
                            AnosExperiencia = 8,
                            Codigo = "CIR-003",
                            Especialidad = "Cirugía Laparoscópica",
                            Estado = "Activo",
                            Nombre = "Dr. Luis Quispe"
                        },
                        new
                        {
                            Id = 4,
                            AnosExperiencia = 12,
                            Codigo = "CIR-004",
                            Especialidad = "Traumatología",
                            Estado = "Activo",
                            Nombre = "Dra. Patricia Mamani"
                        },
                        new
                        {
                            Id = 5,
                            AnosExperiencia = 20,
                            Codigo = "CIR-005",
                            Especialidad = "Oncología Quirúrgica",
                            Estado = "Activo",
                            Nombre = "Dr. Fernando Soria"
                        },
                        new
                        {
                            Id = 6,
                            AnosExperiencia = 6,
                            Codigo = "CIR-006",
                            Especialidad = "Anestesiología",
                            Estado = "Activo",
                            Nombre = "Dra. Carmen Flores"
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.EquipoMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<bool>("EstadoOperativo")
                        .HasColumnType("boolean")
                        .HasColumnName("estado_operativo");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fabricante");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UltimoMantenimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_mantenimiento");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("equipos_medicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "EQ-001",
                            Estado = "Activo",
                            EstadoOperativo = true,
                            Fabricante = "Bovie Medical",
                            Nombre = "Bisturí Eléctrico",
                            UltimoMantenimiento = new DateTime(2024, 12, 16, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "EQ-002",
                            Estado = "Activo",
                            EstadoOperativo = true,
                            Fabricante = "Mindray",
                            Nombre = "Monitor de Signos",
                            UltimoMantenimiento = new DateTime(2024, 12, 31, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "EQ-003",
                            Estado = "Activo",
                            EstadoOperativo = true,
                            Fabricante = "Stryker",
                            Nombre = "Laparoscopio HD",
                            UltimoMantenimiento = new DateTime(2025, 1, 8, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "EQ-004",
                            Estado = "Activo",
                            EstadoOperativo = false,
                            Fabricante = "Dräger",
                            Nombre = "Respirador UCI",
                            UltimoMantenimiento = new DateTime(2024, 12, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "EQ-005",
                            Estado = "Activo",
                            EstadoOperativo = true,
                            Fabricante = "Maquet",
                            Nombre = "Mesa de Operaciones",
                            UltimoMantenimiento = new DateTime(2024, 11, 16, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alergias");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("DiagnosticoPre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnostico_pre");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("GrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("grupo_sanguineo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("pacientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alergias = "Penicilina",
                            Codigo = "PAC-001",
                            DiagnosticoPre = "Apendicitis aguda",
                            Edad = 45,
                            Estado = "Activo",
                            GrupoSanguineo = "O+",
                            Nombre = "Juan Pérez Mamani"
                        },
                        new
                        {
                            Id = 2,
                            Alergias = "Ninguna",
                            Codigo = "PAC-002",
                            DiagnosticoPre = "Colecistitis crónica",
                            Edad = 32,
                            Estado = "Activo",
                            GrupoSanguineo = "A+",
                            Nombre = "María López Flores"
                        },
                        new
                        {
                            Id = 3,
                            Alergias = "Ibuprofeno",
                            Codigo = "PAC-003",
                            DiagnosticoPre = "Hernia inguinal derecha",
                            Edad = 58,
                            Estado = "Activo",
                            GrupoSanguineo = "B-",
                            Nombre = "Carlos Ruiz Torrez"
                        },
                        new
                        {
                            Id = 4,
                            Alergias = "Ninguna",
                            Codigo = "PAC-004",
                            DiagnosticoPre = "Fractura de fémur",
                            Edad = 27,
                            Estado = "Activo",
                            GrupoSanguineo = "AB+",
                            Nombre = "Ana Condori Huanca"
                        },
                        new
                        {
                            Id = 5,
                            Alergias = "Aspirina",
                            Codigo = "PAC-005",
                            DiagnosticoPre = "Tumor gástrico",
                            Edad = 61,
                            Estado = "Activo",
                            GrupoSanguineo = "O-",
                            Nombre = "Luis Quispe Mamani"
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.ProcedimientoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer")
                        .HasColumnName("equipo_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoUso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_uso");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("integer")
                        .HasColumnName("procedimiento_id");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EquipoId");

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("procedimientos_equipo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PE-001",
                            EquipoId = 1,
                            Estado = "Activo",
                            EstadoUso = "En uso",
                            Observaciones = "Modo corte activo",
                            ProcedimientoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "PE-002",
                            EquipoId = 2,
                            Estado = "Activo",
                            EstadoUso = "En uso",
                            Observaciones = "Monitoreo continuo",
                            ProcedimientoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PE-003",
                            EquipoId = 3,
                            Estado = "Activo",
                            EstadoUso = "Reservado",
                            Observaciones = "Reservado para laparoscopia",
                            ProcedimientoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "PE-004",
                            EquipoId = 1,
                            Estado = "Activo",
                            EstadoUso = "Liberado",
                            Observaciones = "Proceso completado",
                            ProcedimientoId = 3
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "PE-005",
                            EquipoId = 5,
                            Estado = "Activo",
                            EstadoUso = "Reservado",
                            Observaciones = "Mesa reservada para trauma",
                            ProcedimientoId = 4
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.ProcedimientoQuirurgico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoProcedimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_procedimiento");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_fin");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer")
                        .HasColumnName("paciente_id");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("prioridad");

                    b.Property<int>("SalaId")
                        .HasColumnType("integer")
                        .HasColumnName("sala_id");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PacienteId");

                    b.HasIndex("SalaId");

                    b.ToTable("procedimientos_quirurgicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "PROC-001",
                            Estado = "Activo",
                            EstadoProcedimiento = "En curso",
                            HoraFin = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            HoraInicio = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            PacienteId = 1,
                            Prioridad = "Alta",
                            SalaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "PROC-002",
                            Estado = "Activo",
                            EstadoProcedimiento = "Programado",
                            HoraFin = new DateTime(2025, 1, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            HoraInicio = new DateTime(2025, 1, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            PacienteId = 2,
                            Prioridad = "Media",
                            SalaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "PROC-003",
                            Estado = "Activo",
                            EstadoProcedimiento = "Finalizado",
                            HoraFin = new DateTime(2025, 1, 15, 7, 0, 0, 0, DateTimeKind.Utc),
                            HoraInicio = new DateTime(2025, 1, 15, 5, 0, 0, 0, DateTimeKind.Utc),
                            PacienteId = 3,
                            Prioridad = "Baja",
                            SalaId = 3
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "PROC-004",
                            Estado = "Activo",
                            EstadoProcedimiento = "Programado",
                            HoraFin = new DateTime(2025, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            HoraInicio = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            PacienteId = 4,
                            Prioridad = "Alta",
                            SalaId = 4
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "PROC-005",
                            Estado = "Activo",
                            EstadoProcedimiento = "Finalizado",
                            HoraFin = new DateTime(2025, 1, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            HoraInicio = new DateTime(2025, 1, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            PacienteId = 5,
                            Prioridad = "Media",
                            SalaId = 1
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.RolQuirurgico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CirujanoId")
                        .HasColumnType("integer")
                        .HasColumnName("cirujano_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("integer")
                        .HasColumnName("procedimiento_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("CirujanoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("roles_quirurgicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CirujanoId = 1,
                            Codigo = "ROL-001",
                            Estado = "Activo",
                            ProcedimientoId = 1,
                            Rol = "Cirujano Principal"
                        },
                        new
                        {
                            Id = 2,
                            CirujanoId = 2,
                            Codigo = "ROL-002",
                            Estado = "Activo",
                            ProcedimientoId = 1,
                            Rol = "Anestesiólogo"
                        },
                        new
                        {
                            Id = 3,
                            CirujanoId = 3,
                            Codigo = "ROL-003",
                            Estado = "Activo",
                            ProcedimientoId = 2,
                            Rol = "Cirujano Principal"
                        },
                        new
                        {
                            Id = 4,
                            CirujanoId = 6,
                            Codigo = "ROL-004",
                            Estado = "Activo",
                            ProcedimientoId = 2,
                            Rol = "Anestesiólogo"
                        },
                        new
                        {
                            Id = 5,
                            CirujanoId = 1,
                            Codigo = "ROL-005",
                            Estado = "Activo",
                            ProcedimientoId = 3,
                            Rol = "Cirujano Principal"
                        },
                        new
                        {
                            Id = 6,
                            CirujanoId = 4,
                            Codigo = "ROL-006",
                            Estado = "Activo",
                            ProcedimientoId = 4,
                            Rol = "Cirujano Principal"
                        },
                        new
                        {
                            Id = 7,
                            CirujanoId = 5,
                            Codigo = "ROL-007",
                            Estado = "Activo",
                            ProcedimientoId = 5,
                            Rol = "Cirujano Principal"
                        },
                        new
                        {
                            Id = 8,
                            CirujanoId = 2,
                            Codigo = "ROL-008",
                            Estado = "Activo",
                            ProcedimientoId = 5,
                            Rol = "Anestesiólogo"
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.SalaQuirurgica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<string>("NivelEsterilidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel_esterilidad");

                    b.Property<string>("NumeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<DateTime>("UltimaLimpieza")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_limpieza");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("NumeroSala")
                        .IsUnique();

                    b.ToTable("salas_quirurgicas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "SALA-001",
                            Disponible = false,
                            Estado = "Activo",
                            NivelEsterilidad = "Alto",
                            NumeroSala = "Q-01",
                            UltimaLimpieza = new DateTime(2025, 1, 15, 6, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "SALA-002",
                            Disponible = true,
                            Estado = "Activo",
                            NivelEsterilidad = "Medio",
                            NumeroSala = "Q-02",
                            UltimaLimpieza = new DateTime(2025, 1, 15, 3, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "SALA-003",
                            Disponible = true,
                            Estado = "Activo",
                            NivelEsterilidad = "Alto",
                            NumeroSala = "Q-03",
                            UltimaLimpieza = new DateTime(2025, 1, 15, 7, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "SALA-004",
                            Disponible = false,
                            Estado = "Activo",
                            NivelEsterilidad = "Bajo",
                            NumeroSala = "Q-04",
                            UltimaLimpieza = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.TimelineIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Activo")
                        .HasColumnName("estado");

                    b.Property<int>("ProcedimientoId")
                        .HasColumnType("integer")
                        .HasColumnName("procedimiento_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("UsuarioRegistra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuario_registra");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ProcedimientoId");

                    b.ToTable("timeline_incidencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "TL-001",
                            Descripcion = "Procedimiento iniciado sin novedades",
                            Estado = "Activo",
                            ProcedimientoId = 1,
                            Timestamp = new DateTime(2025, 1, 15, 7, 30, 0, 0, DateTimeKind.Utc),
                            Tipo = "Inicio",
                            UsuarioRegistra = "enf.garcia"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "TL-002",
                            Descripcion = "Presión arterial estable 120/80",
                            Estado = "Activo",
                            ProcedimientoId = 1,
                            Timestamp = new DateTime(2025, 1, 15, 7, 45, 0, 0, DateTimeKind.Utc),
                            Tipo = "Observación",
                            UsuarioRegistra = "enf.garcia"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "TL-003",
                            Descripcion = "Sangrado moderado controlado",
                            Estado = "Activo",
                            ProcedimientoId = 1,
                            Timestamp = new DateTime(2025, 1, 15, 7, 55, 0, 0, DateTimeKind.Utc),
                            Tipo = "Incidencia",
                            UsuarioRegistra = "dr.vega"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "TL-004",
                            Descripcion = "Cirugía de hernia iniciada",
                            Estado = "Activo",
                            ProcedimientoId = 3,
                            Timestamp = new DateTime(2025, 1, 15, 5, 0, 0, 0, DateTimeKind.Utc),
                            Tipo = "Inicio",
                            UsuarioRegistra = "enf.morales"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "TL-005",
                            Descripcion = "Cirugía finalizada exitosamente",
                            Estado = "Activo",
                            ProcedimientoId = 3,
                            Timestamp = new DateTime(2025, 1, 15, 7, 0, 0, 0, DateTimeKind.Utc),
                            Tipo = "Fin",
                            UsuarioRegistra = "enf.morales"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "TL-006",
                            Descripcion = "Resección gástrica parcial iniciada",
                            Estado = "Activo",
                            ProcedimientoId = 5,
                            Timestamp = new DateTime(2025, 1, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            Tipo = "Inicio",
                            UsuarioRegistra = "enf.silva"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "TL-007",
                            Descripcion = "Resección completada sin complicaciones",
                            Estado = "Activo",
                            ProcedimientoId = 5,
                            Timestamp = new DateTime(2025, 1, 14, 11, 0, 0, 0, DateTimeKind.Utc),
                            Tipo = "Fin",
                            UsuarioRegistra = "enf.silva"
                        });
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.ProcedimientoEquipo", b =>
                {
                    b.HasOne("Gestion_Quirurgica.Dominio.EquipoMedico", "Equipo")
                        .WithMany("ProcedimientosEquipo")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_Quirurgica.Dominio.ProcedimientoQuirurgico", "Procedimiento")
                        .WithMany("Equipos")
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.ProcedimientoQuirurgico", b =>
                {
                    b.HasOne("Gestion_Quirurgica.Dominio.Paciente", "Paciente")
                        .WithMany("Procedimientos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_Quirurgica.Dominio.SalaQuirurgica", "Sala")
                        .WithMany("Procedimientos")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.RolQuirurgico", b =>
                {
                    b.HasOne("Gestion_Quirurgica.Dominio.Cirujano", "Cirujano")
                        .WithMany("Roles")
                        .HasForeignKey("CirujanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gestion_Quirurgica.Dominio.ProcedimientoQuirurgico", "Procedimiento")
                        .WithMany("Roles")
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cirujano");

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.TimelineIncidencia", b =>
                {
                    b.HasOne("Gestion_Quirurgica.Dominio.ProcedimientoQuirurgico", "Procedimiento")
                        .WithMany("Timeline")
                        .HasForeignKey("ProcedimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Procedimiento");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.Cirujano", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.EquipoMedico", b =>
                {
                    b.Navigation("ProcedimientosEquipo");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.Paciente", b =>
                {
                    b.Navigation("Procedimientos");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.ProcedimientoQuirurgico", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Roles");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("Gestion_Quirurgica.Dominio.SalaQuirurgica", b =>
                {
                    b.Navigation("Procedimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
